### ISSUE TITLE
JOSS Review - Functionality

### ISSUE THREAD

**Issue by winstonyym** [UrbanRuralSystems/ur-scape#9]
[#4664 joss-reviews](https://github.com/openjournals/joss-reviews/issues/4664#issue-1334082133)

I am not able to test the planning and reachability analysis tools as they are not available for world data. The other tools work well. The ur-scape download page requires user credentials to access city level data. Would you be able to share for testing of functionality? I understand that some data might be private due to stakeholder relationships.

**Comment by luyuhao0326** [comment]
@winstonyym thanks for bringing this up to our attention. We can certainly share for the purpose of testing/reviewing. What is the best way to share, perhaps via email?

**Comment by winstonyym** [comment]
@luyuhao0326 great, email will be fine. My email is winstonyym@u.nus.edu.

**Comment by luyuhao0326** [comment]
Hello @winstonyym, unfortunately due to the NDA, we can't share the local city data. However, we have an alternative open-source dataset for you to test the software and there is even a video to guide you and other users. You can access them freely via this [link](https://urstudio.sec.sg/courses/lesson-2-vectors/lesson/how-to-analyse-data-in-ur-scape/?page_tab=files). It might ask you to register for an account first. Let me know if you have any further questions :)

**Comment by winstonyym** [comment]
Hi @luyuhao0326, I totally understand. Thank you for the clear instructions. Overall, I managed to import the Cirebon dataset and tested the package functionalities. I also have to point out that the entire experience from watching the video to analysis was very clear. Snapshots are a really clever and convenient idea! I will proceed to close this issue.
